"""empty message

Revision ID: 922f5f11f2d3
Revises: 5beb3ac45649
Create Date: 2022-08-04 19:41:22.374114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922f5f11f2d3'
down_revision = '5beb3ac45649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
